name: Release Helm Chart

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: chart

jobs:
  build-chart:
    name: Build Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Lint Helm Chart
        run: helm lint .

  semantic-release:
    name: Semantic Release
    needs: build-chart
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config user.name "github"
          git config user.email "github@kubn.dev"

      - name: Install semantic-release
        run: npm install

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          npx semantic-release
          echo "version=$(git tag --points-at HEAD)" >> "$GITHUB_OUTPUT"

  publish-chart:
    name: Publish Helm Chart
    needs: semantic-release
    if: needs.semantic-release.outputs.version != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ needs.semantic-release.outputs.version }}

      - name: Push Helm Chart
        run: |
          VERSION=${{ needs.semantic-release.outputs.version }}
          CHART_NAME=wings
          helm package .
          helm registry login ${{ secrets.REGISTRY_URL }} --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin <<< "${{ secrets.REGISTRY_PASSWORD }}"
          helm push ${CHART_NAME}-${VERSION#v}.tgz oci://${{ secrets.REGISTRY_URL }}
